-- This is a comment --
require("driesverb.plugin-setup")
require("driesverb.core.options")
require("driesverb.core.keymaps")
require("driesverb.core.colorscheme")
require("driesverb.plugins.comment")
require("driesverb.plugins.nvim-tree")
require("driesverb.plugins.lualine")
require("driesverb.plugins.telescope")
require("driesverb.plugins.nvim-cmp")
require("driesverb.plugins.lsp.mason")
require("driesverb.plugins.lsp.lspsaga")
require("driesverb.plugins.lsp.lspconfig")
require("driesverb.plugins.lsp.null-ls")
require("driesverb.plugins.autopairs")
require("driesverb.plugins.tree-sitter")
